name: Docker Image Build

on:
  push:
    branches-ignore:
      - master

jobs:
  build:
    name: 'Build'
    runs-on: windows-latest
    steps:
      - 
        name: Checkout
        uses: actions/checkout@v2
      - 
        name: Get short SHA
        id: slug
        run: echo "::set-output name=sha7::$(echo ${GITHUB_SHA} | cut -c1-7)"
      - 
        name: Get branch name
        run: echo "BRANCH_NAME=$(echo ${GITHUB_REF#refs/heads/} | tr / -)" >> $GITHUB_ENV
      - 
        name: Get repository variable in lowercase
        run: echo "REPOSITORY=$(echo $GITHUB_REPOSITORY | tr '[A-Z]' '[a-z]')" >> $GITHUB_ENV
      - 
        name: Build & Push docker image
        uses: mr-smithers-excellent/docker-build-push@v5
        with:
          registry: ghcr.io
          githubOrg: Atlantiss
          username: ${{ secrets.CR_REGISTRY_USER }}
          password: ${{ secrets.CR_REGISTRY_PAT }}
          image: ${{ env.REPOSITORY }}/${{ env.BRANCH_NAME }}
          dockerfile: Dockerfile

